### ISSUE TITLE
Poll not working

### ISSUE THREAD

**Issue by Amethyst93** [Senither/AvaIre#4]
When issuing the poll command, it just says "Loading Poll" forever. When changing the environment from "production" to "development" in the configuration, this is what I get in the console:

`
info: Unhandled promise: Promise {
  <rejected> { Error: Bad Request (Unknown Emoji)
    at Request.callback (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\index.js:922:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  original: null,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'BAD REQUEST',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"code": 10014, "message": "Unknown Emoji"}',
        read: [Function],
        body: [Object] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'PUT',
        url: 'https://discordapp.com/api/v6/channels/372077623926456321/messages/378595899229732864/reactions/tickYes%3A319985232306765825/@me',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        req: [Object],
        protocol: 'https:',
        host: 'discordapp.com',
        _callback: [Function],
        res: [Object],
        response: [Circular],
        _timeout: 0,
        called: true },
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'PUT /api/v6/channels/372077623926456321/messages/378595899229732864/reactions/tickYes%3A319985232306765825/@me HTTP/1.1\r\nHost: discordapp.com\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: DiscordBot (https://github.com/qeled/discordie, v0.11.0) (Windows_NT 10.0.15063; x64) node/6.11.4 openssl/1.0.2l\r\nAuthorization: Bot MzYzMzU0MjAwOTAzNzc4MzI0.DM_V2g.WB6w44Jg4MzpHGh-mXpfw62seOw\r\nConnection: close\r\nContent-Length: 0\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'PUT',
        path: '/api/v6/channels/372077623926456321/messages/378595899229732864/reactions/tickYes%3A319985232306765825/@me',
        _ended: true,
        parser: null,
        res: [Object] },
     links: {},
     text: '{"code": 10014, "message": "Unknown Emoji"}',
     body: { code: 10014, message: 'Unknown Emoji' },
     files: {},
     buffered: true,
     headers:
      { date: 'Fri, 10 Nov 2017 17:24:56 GMT',
        'content-type': 'application/json',
        'content-length': '43',
        connection: 'close',
        'set-cookie': [Object],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-ratelimit-limit': '1',
        'x-ratelimit-remaining': '0',
        'x-ratelimit-reset': '1510334697',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '3bbab54d7a1e63e5-FRA' },
     header:
      { date: 'Fri, 10 Nov 2017 17:24:56 GMT',
        'content-type': 'application/json',
        'content-length': '43',
        connection: 'close',
        'set-cookie': [Object],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-ratelimit-limit': '1',
        'x-ratelimit-remaining': '0',
        'x-ratelimit-reset': '1510334697',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '3bbab54d7a1e63e5-FRA' },
     statusCode: 400,
     status: 400,
     statusType: 4,
     info: false,
     ok: false,
     redirect: false,
     clientError: true,
     serverError: false,
     error:
      { Error: cannot PUT /api/v6/channels/372077623926456321/messages/378595899229732864/reactions/tickYes%3A319985232306765825/@me (400)
          at Response.toError (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\response.js:106:13)
          at Response.setStatusProperties (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\response.js:183:12)          at new Response (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\response.js:42:8)
          at IncomingMessage.<anonymous> (C:\Bots\REL\AvaIre\Bot\node_modules\superagent\lib\node\index.js:918:22)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:80:11)
          at process._tickDomainCallback (internal/process/next_tick.js:128:9)
        status: 400,
        text: '{"code": 10014, "message": "Unknown Emoji"}',
        method: 'PUT',
        path: '/api/v6/channels/372077623926456321/messages/378595899229732864/reactions/tickYes%3A319985232306765825/@me' },
     accepted: false,
     noContent: false,
     badRequest: true,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 400,
  code: 10014 } }: Error: Bad Request (Unknown Emoji)
`

I see that it says "code: 10014 } }: Error: Bad Request (Unknown Emoji)". I have read that it might have something to do with unicode formatting maybe?

I am using Microsoft Windows 10
Latest Nodejs & NPM

**Comment by Senither** [comment]
The public version of Ava uses two custom emojis for polls which exists on the `AvaIre Central Test Server` Discord server, since your bot is not on this server your bot is unable to find the emojis it's looking for.
You can see the emojis in this picture: https://media.senither.com/7LR1rh23
An easy fix would just be to change the emojis the bot is looking for when using the poll command, you can do that by going to line [__29__](https://github.com/avaire/avaire/blob/master/app/bot/commands/utility/CreateYesNoPollCommand.js#L29) and line [__39__](https://github.com/avaire/avaire/blob/master/app/bot/commands/utility/CreateYesNoPollCommand.js#L39) in the [CreateYesNoPoolCommand file](https://github.com/avaire/avaire/blob/master/app/bot/commands/utility/CreateYesNoPollCommand.js)
The emoji objects should look like this:

```javascript
/**
 * The yes emoji.
 *
 * @type {Object}
 */
this.yesEmoji = {
    id: '319985232306765825',
    name: 'tickYes'
};

/**
 * The no emoji.
 *
 * @type {Object}
 */
this.noEmoji = {
    id: '319985629750624257',
    name: 'tickNo'
};
```

Just pick two emojis, one for yes, and one for no, enter their ID and name and you should be good to go.

**Comment by Amethyst93** [comment]
Thank you for this fast response, I really apreciate it. Noob question though: Let's say I want to put the :x: ( : x : ) emoji for tickNo. How do I get the ID of that particular emoji, and do I have to put 'x' in there for name, or something else?

**Comment by Senither** [comment]
👋 No worries, went off to get dinner so here is the not so fast response to your second question :p 
If you have the Discord Developer mode enabled (_[Click here to see how to enable it](https://media.senither.com/UKuLRG)_) you can right click any emoji, user, channel, etc to get the ID, example: https://media.senither.com/AGR48TF
So to use a custom emoji all you need to do is copy the ID via developer mode, and use the emoji name, so in your case, you could use `x` if you use the emoji like `:x:`
Hope that helps^^

**Comment by Amethyst93** [comment]
Still fast IMO! I knew that you can copy the ID of stuff on discord with developer mode, but I actualy tried to use it with : x : and it didn't work for some reason, but I *just* made the discovery that it works with custom added emojis! So, thank you very very much for your help! :D This issue can be closed now.

**Comment by Senither** [comment]
👍 Nice you got it working^^ Yeah I never actually did test if it works with default Discord emojis since Ava has always used custom emojis, welp rip that's my bad, nice you got it working tho^^
